version: "3.6"
services:
  nginx:
    image: alenx/walle-web:2.1
    container_name: walle-nginx
    hostname: walle-nginx
    ports:
      - "80:80"
    depends_on:
      - python
    networks:
      - walle-net

  python:
    image: alenx/walle-python:2.1
    container_name: walle-python
    hostname: walle-python
    env_file:
      - ./walle.env
    command: bash -c "cd /opt/walle_home/ && /bin/bash admin.sh migration &&  python waller.py"
    expose:
      - "5000"
    volumes:
      - /opt/walle_home/plugins/:/opt/walle_home/plugins/
      - /opt/walle_home/codebase/:/opt/walle_home/codebase/
      - /opt/walle_home/logs/:/opt/walle_home/logs/
      - /root/.ssh:/root/.ssh/
    depends_on:
      - mysql
    networks:
      - walle-net

  mysql:
    image: mysql:5.6
    container_name: walle-mysql
    hostname: walle-mysql
    env_file:
      - ./walle.env
    command: ['--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /data/walle/mysql:/var/lib/mysql
    networks:
      - walle-net

networks:
  walle-net:
    driver: bridge
